# Generated by Django 3.2.16 on 2023-01-14 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('data_json', models.JSONField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('overall_status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='OCR_Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KGEprocess.data')),
            ],
            options={
                'db_table': 'ocr_queue',
            },
        ),
    ]
